# Generated by Django 3.0.3 on 2020-04-07 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_groupstudents'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupStudents',
        ),
    ]
